// app/utils/seo.ts
// Single source of truth for site-wide SEO constants.
// Import these instead of hardcoding the domain/name/image in individual pages.

export const SITE_URL = 'https://rungorun.store'
export const SITE_NAME = 'Run Go Run'
export const DEFAULT_OG_IMAGE = `${SITE_URL}/og-image.jpg`
export const DEFAULT_LOGO_IMAGE = `${SITE_URL}/apple-touch-icon.png`
export const DEFAULT_DESCRIPTION =
  "Engineered running gear built for Accra's heat and hustle. Vests, armbands, shorts, and gear made for runners who earn it every day. Shop rungorun.store."

export const absoluteUrl = (path: string) => `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`

// Broad, on-topic keyword coverage. Note: Google ignores the `keywords` meta tag entirely
// (has since 2009) — this exists for the minor weight Bing/Yandex still give it, and to keep
// the term list centralized rather than repeated/stuffed per page. What actually moves search
// rankings is unique page titles/descriptions/content and real content depth (e.g. blog posts).
export const BASE_KEYWORDS = [
  // Core gear & shopping intent
  'running gear Accra',
  'jogging gear Ghana',
  'running vest Accra',
  'jogging vest',
  'phone armband for running',
  'running armband Ghana',
  'running accessories Ghana',
  'jogging accessories Accra',
  'runner accessories',
  'running apparel Ghana',
  'jogging apparel Accra',
  'running clothes Ghana',
  'jogging outfit',
  'sportswear Accra',
  'sportswear Ghana',
  'athletic wear Ghana',
  'workout gear Accra',
  'workout accessories Ghana',
  'fitness gear Ghana',
  'fitness accessories Accra',
  'exercise gear Ghana',
  'cardio gear Accra',
  // Buying & local intent
  'buy running gear online Ghana',
  'running gear delivery Accra',
  'running store Ghana',
  'jogging store Accra',
  'WhatsApp shopping running gear',
  'best running gear Accra',
  'running gear for hot weather',
  'jogging gear for humidity',
  // Training & how-to
  'how to start jogging',
  'jogging tips Accra',
  'running tips Ghana',
  'marathon training gear',
  '5k training gear',
  'running gear for beginners',
  'running training guide',
  'running gear reviews',
  'morning run gear',
  'early morning jogging gear',
  // Community & lifestyle
  'Accra running community',
  'Ghana running brand',
  'jogging community Ghana',
  'run club Accra',
  'active lifestyle Ghana',
  'active living Accra',
  'fitness lifestyle Ghana',
  'keep fit Ghana',
  'keeping fit Accra',
  'running gear for runners',
  // Product specifics
  'running shorts Ghana',
  'running socks Accra',
  'moisture wicking running gear',
  'breathable running vest',
  'reflective running gear',
  'running hydration gear',
  'running waist pouch',
  'sports armband for phone',
  'running headband',
  'compression gear running',
  'running gloves Accra',
  'no-slip phone armband',
  'sweat proof running gear',
  'running gear for men Ghana',
  'running gear for women Ghana',
  'unisex running gear',
  // Climate-specific
  'running gear for tropical climate',
  'humidity proof workout gear',
  'breathable jogging clothes',
  'sun protection running gear',
  'lightweight running gear',
  // Health & wellness
  'benefits of jogging',
  'running for weight loss',
  'jogging for beginners guide',
  'cardio workout at home',
  'outdoor cardio Ghana',
  'healthy lifestyle Ghana',
  'wellness Ghana',
  'movement is medicine',
  'active recovery gear',
  'injury prevention running',
  // Local geography
  'running routes Accra',
  'jogging spots Accra',
  'Tema running gear',
  'East Legon running store',
  'Kumasi running gear',
  'running gear Kasoa',
  // Activity types
  'track and field gear Ghana',
  'athletics gear Ghana',
  'sprinting gear',
  'half marathon training gear',
  '10k training gear',
  'race day gear',
  'trail running gear Ghana',
  'treadmill workout gear',
  'urban running gear',
  'night running gear',
  'reflective jogging gear',
  'running safety gear',
  'Ghanaian running brand',
  // Accra jogging hotspots & routes
  'El Wak Stadium running track',
  'Independence Square jogging',
  'Black Star Square morning run',
  'University of Ghana Legon running track',
  'Aburi Botanical Gardens jogging trail',
  'Achimota Forest running trail',
  'Labadi Beach jogging',
  'La Beach morning run',
  'Airport Residential Area running route',
  'Trasacco Valley jogging route',
  'Roman Ridge running route',
  'Ridge Accra jogging route',
  'Efua Sutherland Park running',
  'Accra Sports Stadium running track',
  'Dzorwulu jogging route',
  'Kwame Nkrumah Circle jogging',
  'Cantonments running route',
  'Osu jogging route',
  'North Ridge running spot',
  'Spintex Road morning jog',
  // Health & wellness benefits
  'health benefits of running',
  'cardiovascular benefits of running',
  'mental health benefits of running',
  'running for stress relief',
  'running for heart health',
  'jogging for weight loss',
  'running boosts immune system',
  'running for mental clarity',
  'jogging reduces stress',
  'benefits of morning run',
  'running for longevity',
  'jogging for diabetes prevention',
  'running for better sleep',
  "runner's high",
  'running for stamina',
  'jogging for energy boost',
  'benefits of outdoor exercise',
  'running for bone health',
  'jogging for blood pressure',
  'running for lung capacity',
  'running for mental wellbeing',
  'jogging for anxiety relief',
  'running for muscle tone',
  'daily jogging benefits',
  'running for a healthy heart',
  // More gear specifics
  'running belt',
  'running sunglasses',
  'no chafe running gear',
  'blister prevention socks',
  'running cap Ghana',
  'sun hat for running',
  'cooling towel for running',
  'hydration vest running',
  'running backpack',
  'fitness tracker armband',
  'waterproof phone pouch running',
  'anti-chafe running gear',
  'quick dry running shirt',
  'breathable running shorts',
  'high visibility running gear',
  'running gear for rainy season',
  'running gear for beginners Ghana',
  'durable running gear',
  'comfortable running gear',
  'affordable running gear Ghana',
  'premium sportswear Ghana',
  'running gear for students Ghana',
  'running gear for women beginners',
  'running gear for men beginners',
  'stylish running gear Ghana',
  // Training & technique
  'jogging routine for beginners',
  'running schedule for beginners',
  'couch to 5k Ghana',
  'interval training running',
  'tempo run tips',
  'long distance running gear',
  'sprint training gear',
  'HIIT running gear',
  'running warm up tips',
  'running cool down tips',
  'stretching for runners',
  'proper running technique',
  'running pace tips',
  'nutrition for runners',
  'post-run recovery tips',
  // Community, events & general terms
  'Accra marathon',
  'Milo marathon Ghana',
  'charity run Accra',
  '5k run Accra',
  '10k race Ghana',
  'fun run Accra',
  'sunrise run Accra',
  'group jogging Accra',
  'running buddy Accra',
  'social running club Ghana',
  'running',
  'jogging',
  'marathon',
  'track running',
  'road running',
]

export const keywordsMeta = (extra: string[] = []) => ({
  name: 'keywords',
  content: [...extra, ...BASE_KEYWORDS].join(', '),
})
